require:
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
  - 'bin/**/*'
  - 'config/**/*.rb'
  - 'db/**/*.rb'
  - 'features/**/*.rb'
  - 'lib/**/*.rake'
  - 'vendor/bundle/**/*'

Rails:
  Enabled: true

# `if foo = some_method` is too useful to give up
Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120
